optin.d/eins/config/routes.rb
Rails.application.routes.draw do
  
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  
  resources :optouts
  resources :pages
  resources :optins do
    member do # beware token will be id!
      get 'pending'
      get 'confirm'
      get 'confirmed'      
    end
  end  
  
  get 'mno_lookup/:mobile' => 'mno_lookup#lookup'
  
  root 'optins#new'
    
end

optin.d/eins/app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

optin.d/eins/app/models/optin.rb
class Optin < ActiveRecord::Base
    
  has_one :voucher
    
  validates_format_of     :mobile, with: /\A[0-9 \-]+\z/, :message =>  :please_enter_correct_number, on: :create
  validates_length_of     :mobile, :minimum => 8, :maximum => 20, :message => :please_enter_correct_number,  on: :create
  validates_acceptance_of :terms, :message => :please_accept_terms_and_conditions
  validates_presence_of   :country_code, :message => :please_enter_country_code  
  validates_uniqueness_of :mobile, :scope => [:country_code], :message => :already_registered, on: :create

  validates_with Zeopt::OptinEmbargoValidator, 
    max_optouts: ZEOPT['optin_embargo_max_optouts'], 
    minimal_time: ZEOPT['minimal_optin_time']

  before_create :set_token
  
  #
  #
  def mobile=(value)
    self[:mobile] = Zeopt::Mobile.remove_trailing_zeros value
  end

  #
  #
  def register_double_optin hostname
    self.has_optin = true
    self.hostname = hostname
  end

  #
  #
  def register_optout user_comment
    self.optout = true
    self.optout_time = Time.now
    # don't use setter, it can change this by remove_trailing_zeros
    self[:mobile] = Optin.hashed_number self.country_code, self.mobile
    self.user_comment = user_comment
  end

  #
  #
  def self.hashed_number country_code, mobile
     Zeopt::Mobile.hash_value "#{country_code}#{mobile}"
  end

  private
  
  #
  #
  def set_token
    self.token = SecureRandom.urlsafe_base64(nil, false)
  end
    
end

optin.d/eins/app/models/voucher.rb
class Voucher < ActiveRecord::Base
  belongs_to :optin
  validates_uniqueness_of :code
  
  #
  #
  def self.available?
    Voucher.where(optin_id: nil).count >= ZEOPT['min_residual_vouchers']
  end
  
  #
  # returns next free voucher code and assigns optin id, returns nil if no voucher left
  #
  def self.take_voucher optin
  
    Voucher.transaction do    
     if voucher = Voucher.where(optin_id: nil).order(:created_at).first
       voucher.update_attribute :optin_id, optin.id
       voucher
     end
    end
  end
  

  #
  #
  def self.invalid_vouchers 

    # TODO: add optoutdate to model
    vouchers = Voucher.includes(:optin)
    vouchers = vouchers.where("optins.optout" => true)
    vouchers = vouchers.where(["optins.optout_time - optins.created_at <= interval '? hours'", 24])
    vouchers = vouchers.where(["optins.created_at >= ?",Time.now - 24.hours])
    vouchers
  end
  
end

optin.d/eins/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

optin.d/eins/app/controllers/mno_lookup_controller.rb
class MnoLookupController < ApplicationController
  #
  #
  def lookup    
    @result = Zeopt::Mobile.validate_mno "#{params[:mobile]}", ZEOPT['mno_lookup_mccmnc']
  end
end

optin.d/eins/app/controllers/optins_controller.rb
class OptinsController < ApplicationController

  before_action :optin_by_token, only: [:pending, :confirm, :confirmed]
  
  #
  #
  def index
    redirect_to new_optin_path
  end

  #
  #
  def new    
    # check if there are enough voucher codes left to be played out
    @optin = Optin.new if Voucher.available?    
  end
  
  #
  #
  def create    
    @optin = Optin.new optin_params

    if (not params[:mno_checked] == 'true') and @optin.valid?
      params[:lookup] = true 
      render "new"
      return
    end

    if @optin.save      
      if Zeopt::Sms.send_sms @optin
        @optin.update_attribute :sms_sent, true
        redirect_to pending_optin_path(@optin.token)
        return
      else
        # ja was dann? 
        @optin.errors.add( :base, I18n.t('sms.could_not_be_sent') )
      end
    end        
    render "new"
  end
  
  #
  #
  def pending
  end

  
  #
  #
  def confirm
    @optin.register_double_optin Zeopt::Mobile.resolv_hostname(request)

    if @optin.save
      redirect_to confirmed_optin_path(@optin.token)
    else
      raise "could not safe optin #{@optin.id} for confirmation"
    end
  end
  
  #
  #
  def confirmed
    unless @voucher = Voucher.find_by_optin_id(@optin.id)
      @voucher = Voucher.take_voucher @optin
    end
  end
    
  private 
  
  #
  #
  def optin_by_token
    @optin = Optin.find_by_token(params[:id])
    raise "no optin found" unless @optin
    @optin
  end
  
  #
  #
  def optin_params
    params.require(:optin).permit(:mobile, :tracked_advertiser_id, :terms, :transaction_id, :country_code, :user_comment)
  end
  
end

optin.d/eins/app/controllers/optouts_controller.rb
#
#
class OptoutsController < ApplicationController
  
  #
  #
  def index
    redirect_to new_optout_path
  end
  
  #
  #
  def new  
    @optin = Optin.new
  end

  #
  #
  def create
    form = Optin.new optin_params
    optin = Optin.where(country_code: form.country_code, mobile: Zeopt::Mobile.remove_trailing_zeros(form.mobile)).first

    if optin
      optin.register_optout params[:user_comment]
      optin.save!
      redirect_to action: 'show', id: optin.token
    else
      @optin = form
      @optin.errors.add( :mobile, :mobile_not_found )
      render 'new'
    end
  end
  
  #
  #
  def show
    @optin = Optin.find_by_token(params[:id])
    raise "no optin found" unless @optin    
  end
  
  private
  
  #
  #
  def optin_params
    params.require(:optin).permit(:mobile, :country_code, :user_comment)
  end
  
end

optin.d/eins/app/controllers/pages_controller.rb
class PagesController < ApplicationController

  
  #
  #
  def show
    render action: params[:id]
  end

end

optin.d/eins/app/helpers/application_helper.rb
module ApplicationHelper

  #
  #
  def transaction_id_params    
    if (params[:optin])
      t_id = params[:optin][:transaction_id] ? params[:optin][:transaction_id] : ""
    else
      t_id = params[:transaction_id] ? params[:transaction_id] : ""
    end
    t_id
  end

  #
  #
  def generate_country_code_array(codestr)
    a = codestr.gsub(" ","").split(",")
    a.map{|k| "+"+k }.zip(a)
  end
  
end

optin.d/eins/app/views/admin/_line_graph.haml
= javascript_include_tag "//www.google.com/jsapi", "chartkick"
= line_chart metric 

optin.d/eins/app/views/layouts/application.html.haml
!!!
/[if lt IE 7] <html class="no-js lt-ie9 lt-ie8 lt-ie7">
/[if IE 7] <html class="no-js lt-ie9 lt-ie8">
/[if IE 8] <html class="no-js lt-ie9">
/ [if gt IE 8]><!
%html.no-js
  / <![endif]
  %head
    %meta{:charset => "utf-8"}/
    %meta{:content => "IE=edge,chrome=1", "http-equiv" => "X-UA-Compatible"}/
    %title= t('.title')
    %meta{:content => "", :name => "description"}/
    %meta{:content => "width=device-width,initial-scale=1", :name => "viewport"}/
    %link{:href => "//fonts.googleapis.com/css?family=Arvo:400", :rel => "stylesheet", :type => "text/css"}/
    %link{:href => "//fonts.googleapis.com/css?family=Open+Sans", :rel => "stylesheet", :type => "text/css"}/
    = stylesheet_link_tag 'application', media: 'all'

    /[if lt IE 9]
      <script src="//html5shiv.googlecode.com/svn/trunk/html5.js"></script>      
    = javascript_include_tag 'application'
    = csrf_meta_tags
    
  /%body#optimo-startpage
  %body
    #optimo-header        
      #header-container          
        #header-logo= link_to image_tag("logo.png"), root_path          
        #headline-text= t('.headline')
    
    = yield
    
    %section
      #nav        
        %ul
          %li= link_to t('.home'),    '/'
          %li= link_to t('.imprint'), '/pages/imprint'
          %li= link_to t('.privacy'), '/pages/privacy'
          %li= link_to t('.faq'),     '/pages/faq'
          %li= link_to t('.terms'),   '/pages/terms'
          %li= link_to t('.optout'),  new_optout_path

    

optin.d/eins/app/views/mno_lookup/lookup.js.haml
- if @result == 1 
  $('#mno_checked').val('true');
  $('#new_optin').submit();

- else
  - html = I18n.t ('mno_lookup.result_not_valid') if @result == 0
  - html ||= I18n.t ('mno_lookup.result_error')

  // display error 
  $('#wait_image').hide();
  $('#submit_button').show();
  $('#mno_error').show()
  $('#mno_error').html('#{j html}');

optin.d/eins/app/views/optins/_form.html.haml
= form_for @optin do |f|

  = hidden_field_tag :mno_checked, false

  .box
    - if @optin.errors.any?
      #error_explanation
        %h2= "#{t(:error, count: @optin.errors.messages.count)}"
        %ul
          - @optin.errors.messages.each do |msg|
            %li= msg.second.first

    %p
      = render partial: 'shared/mobile_input', locals: { f: f }
    
    %p
      = f.hidden_field :tracked_advertiser_id, value: "new-zeotap"
      = f.hidden_field :transaction_id, value: transaction_id_params

    %p
      #terms              
        = f.check_box :terms

        = t('.terms_confirmation', link: link_to(t('.terms'), '/pages/terms')).html_safe

        = f.submit t('.submit'), id: "submit_button"

        %a{ name: "buttonmarker" }
      
      #wait_image= image_tag("ajax-loader.gif")

      #mno_error

:javascript
  terms = $("#optin_terms");
  terms.unbind('click').click(function(){

    if (terms.prop('checked')) {
      terms.fancybox({
        width: 500,
        maxWidth: 500,
        closeBtn: false,
        modal: true,
        content: "#{j render partial: 'terms'}",
        afterClose: function() {
          if (terms.prop('checked')) {
            terms.prop('checked', false);
            terms.unbind('fancybox');
          } else {                        
            terms.prop('checked', true);
          }
        }
      });
    } else {
      terms.fancybox({
        content: "#{I18n.t('optins.terms_popup.withdrawal')}",
        afterClose: function() {
          terms.prop('checked',false);
        }
      });
    }
  });
    
- if params[:lookup]
  :javascript
    // show status bar      
    $('#wait_image').show()    
    $('#submit_button').hide()
    window.location = window.location.href + "#buttonmarker";
    var mobile = $('#optin_country_code').val() + $('#Mobilfunknummer').val();
    var url = '/mno_lookup/' + mobile;
    $.get(url);
  

optin.d/eins/app/views/optins/_terms.html.haml
.terms-popup
  = render partial: 'shared/terms'
  
  %div{align:"center"}
    %a#confirm= I18n.t('optins.terms_popup.confirm')
  
:javascript
  $('#confirm').click(function(){
    $.fancybox.close();
  });

optin.d/eins/app/views/optins/confirmed.html.haml
%section
  %h1= t('.headline')
    
  #whitespace
    &nbsp;
    #keyvisual= image_tag 'key-visual.png', width: 600

  #content
    %p#notice
      = t('.info', mailto: '<a href="mailto:info@zeotap.com">info@zeotap.com</a>' ).html_safe
    ="liefer held voucher code: #{@voucher.code}"
      

optin.d/eins/app/views/optins/new.html.haml
%section
  %h1= t('.headline')
%section     
  .content-right
    #content
      %p
        %ul
          - t('.benefits').each do |benefit|
            %li= benefit
      
    %p#notice= notice

    - if @optin
      #signup
        = render partial: 'form'
    - else
      = t('.voucher_campaign_expired')

#key-visual
  = image_tag 'key-visual.png'

optin.d/eins/app/views/optins/pending.html.haml
%section
  %h1= t('.headline')    
    
  #whitespace
    &nbsp;
    #keyvisual= image_tag 'key-visual.png', width: 600
    
  #content
    %p= t('.info')

optin.d/eins/app/views/optouts/new.html.haml
%section
  %h1#static-page
    = t( '.headline')
%section
  .content-right
    #content
      %p#notice= notice
      %p= t( '.info' )

      #signup
        = form_for @optin, url: optouts_path do |f|
          .box
            - if @optin.errors.any?
              #error_explanation
                %h2= "#{t(:error, count: @optin.errors.messages.count)}"
                %ul
                  - @optin.errors.full_messages.each do |msg|
                    %li= msg
            %p              
              = render partial: 'shared/mobile_input', locals: { f: f }
              %br
              %label= t( '.comment' )

              = f.text_area :user_comment, id: "Kommentar", placeholder: t( '.placeholder'), 
                size: "50x8", style: "resize:none"
          %p
            = f.submit t( '.submit' )
          

optin.d/eins/app/views/optouts/show.html.haml
%section
  %h1= t('.headline')
    
  #whitespace
    &nbsp;
    #keyvisual
      = image_tag 'key-visual.png', width: 600
  #content
    %p= t('.info')
      
    

  

optin.d/eins/app/views/pages/faq.html.haml
%section#main
  %h1#static-page= t('.headline')

  - t('.items').each do |item|
    %h2= item[:title]
    %p= item[:text]

optin.d/eins/app/views/pages/imprint.html.haml
%section#main
  %h1#static-page= t('.headline') 
%section  
  #static-box
    BD Internet GmbH 
    %br
    c/o HitFox GmbH 
    %br
    Rosenstraße 17 
    %br
    10178 Berlin 
    %br
    %br
    Amtsgericht Charlottenburg; HRB 158127 B 
    %br
    USt-Id.: DE295498059 
    %br
    %br
    Geschäftsführer: Hendrik Krawinkel 
    %br
    %a{href: "mailto:info@zeotap.com"} info@zeotap.com
  

optin.d/eins/app/views/pages/privacy.html.haml
%section#main
  %h1#static-page= t('.headline')    
  #static-box
    - t('.paragraphs').each do |paragraph|
      %p= paragraph.html_safe

optin.d/eins/app/views/pages/terms.html.haml
%section#main

= render partial: 'shared/terms'

optin.d/eins/app/views/shared/_mobile_input.html.haml
%label= t('.label')
%br
= f.select :country_code, ZEOPT['country_codes'].map{|cc| ["+#{cc}", "#{cc}"]}
= f.text_field :mobile, id: "Mobilfunknummer", placeholder: t('.mobile_placeholder')

optin.d/eins/app/views/shared/_terms.html.haml
%section#main
  %h1#static-page= t('.headline')
  #static-box
    - t('.paragraphs').each do |paragraph|
      %p= paragraph.html_safe